version: '3.5'

services:
  redis:
    image: redis
  backend:
    image: backend
    environment:
      - FRONT_URL=http://localhost:5000
      - REDIS=redis
    ports:
      - 8000:8000
  frontend:
    image: frontend
    environment:
      - API_URL=http://localhost:8000
    ports:
      - 5000:5000
