version: '3.5'

services:
  training:
    image: ml-training
    volumes:
      - imgs:/src/imgs
      - model:/src/model
  backend:
    image: ml-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
  frontend:
    image: ml-frontend
    ports:
      - 3000:3000

volumes:
  model:
  imgs:
